# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configure',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
