# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='space',
        ),
    ]
