# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_remove_storage_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='mount',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='storage',
            name='path',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
