# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20160420_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('cpu', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('istemplate', models.CharField(default='No', max_length=10)),
                ('templatename', models.CharField(default='', max_length=32)),
                ('templatepath', models.CharField(default='', max_length=128)),
                ('nic1', models.CharField(default='', max_length=32)),
                ('nic2', models.CharField(default='', max_length=32)),
                ('disk1', models.CharField(default='', max_length=128)),
                ('disk2', models.CharField(default='', max_length=128)),
                ('snapshotname', models.CharField(default='', max_length=32)),
                ('snapshotpath', models.CharField(default='', max_length=128)),
                ('yourself', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
