# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_vm'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='user',
            field=models.CharField(default='admin', max_length=32),
        ),
    ]
