# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0009_auto_20160507_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmPort',
            fields=[
                ('vmname', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('port', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AlterField(
            model_name='vm',
            name='istemplate',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
