# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0010_auto_20160523_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmport',
            name='mapport',
            field=models.IntegerField(default=-1),
        ),
    ]
