# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0011_vmport_mapport'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmIso',
            fields=[
                ('vmname', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('iso', models.CharField(default='', max_length=256)),
                ('path', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
