# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('identify', models.CharField(max_length=20)),
            ],
        ),
    ]
